kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-log-forwarders
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-operators
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterlogforwarders.logging.openshift.io-v1-admin
