apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: perficient-operators
  namespace: openshift-operators
spec:
  displayName: Perficient Operators
  image: quay.io/mrethers/operators-catalog:latest
  publisher: Perficient
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 5m