kind: Secret
apiVersion: v1
metadata:
  generateName: gitops-repo-creds-
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  password: ${CONFIG_REPO_PASSWORD}
  url: ${CONFIG_REPO_URL}
  username: ${CONFIG_REPO_USERNAME}
type: Opaque